# Generated by Django 4.1.5 on 2023-02-08 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher_date',
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 13, 13, 28, 638872)),
        ),
    ]
