# Generated by Django 4.1.5 on 2023-02-08 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_book_id_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 13, 55, 59, 977065)),
        ),
    ]
