# Generated by Django 4.1.5 on 2023-03-17 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_creation_date'),
        ('products', '0018_alter_comment_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('shipping_address', models.CharField(max_length=254)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authentication.user')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('created_by', 'created_for')},
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedLine', to='products.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderLine', to='products.order')),
            ],
        ),
    ]
