# Generated by Django 4.1.5 on 2023-04-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_order_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
